"""SQLite authority barriers shared by Alembic and create_all."""
TRIGGERS = {
"trg_snapshot_update": "BEFORE UPDATE ON detection_snapshots BEGIN SELECT RAISE(ABORT,'referenced snapshot immutable') WHERE EXISTS(SELECT 1 FROM submissions WHERE detection_snapshot_id=OLD.id); END",
"trg_snapshot_delete": "BEFORE DELETE ON detection_snapshots BEGIN SELECT RAISE(ABORT,'referenced snapshot immutable') WHERE EXISTS(SELECT 1 FROM submissions WHERE detection_snapshot_id=OLD.id); END",
"trg_state_insert": "BEFORE INSERT ON detection_snapshot_states BEGIN SELECT RAISE(ABORT,'referenced state immutable') WHERE EXISTS(SELECT 1 FROM submissions WHERE detection_snapshot_id=NEW.snapshot_id); END",
"trg_state_update": "BEFORE UPDATE ON detection_snapshot_states BEGIN SELECT RAISE(ABORT,'referenced state immutable') WHERE EXISTS(SELECT 1 FROM submissions WHERE detection_snapshot_id=OLD.snapshot_id); END",
"trg_state_delete": "BEFORE DELETE ON detection_snapshot_states BEGIN SELECT RAISE(ABORT,'referenced state immutable') WHERE EXISTS(SELECT 1 FROM submissions WHERE detection_snapshot_id=OLD.snapshot_id); END",
"trg_submission_frozen": "BEFORE UPDATE ON submissions WHEN NEW.video_id IS NOT OLD.video_id OR NEW.detection_snapshot_id IS NOT OLD.detection_snapshot_id OR NEW.attempt_no IS NOT OLD.attempt_no OR NEW.source_annotation_version IS NOT OLD.source_annotation_version OR NEW.source_media_revision IS NOT OLD.source_media_revision OR NEW.source_video_filename IS NOT OLD.source_video_filename OR NEW.source_storage_key IS NOT OLD.source_storage_key OR NEW.source_video_sha256 IS NOT OLD.source_video_sha256 OR NEW.source_file_size IS NOT OLD.source_file_size OR NEW.source_mtime_ns IS NOT OLD.source_mtime_ns OR NEW.source_device IS NOT OLD.source_device OR NEW.source_inode IS NOT OLD.source_inode OR (NEW.submitted_by IS NOT OLD.submitted_by AND NOT (OLD.submitted_by IS NOT NULL AND NEW.submitted_by IS NULL)) OR NEW.submitted_at IS NOT OLD.submitted_at OR NEW.legacy_backfill IS NOT OLD.legacy_backfill BEGIN SELECT RAISE(ABORT,'submission immutable'); END",
"trg_submission_lifecycle": "BEFORE UPDATE OF status,decided_at ON submissions WHEN NOT ((NEW.status=OLD.status AND NEW.decided_at IS OLD.decided_at) OR (OLD.status='submitted' AND NEW.status='withdrawn' AND NEW.decided_at IS OLD.decided_at) OR (OLD.status='submitted' AND NEW.status IN ('approved','rejected') AND NEW.decided_at IS NOT NULL) OR (OLD.status='approved' AND NEW.status='superseded' AND NEW.decided_at IS OLD.decided_at)) BEGIN SELECT RAISE(ABORT,'invalid submission lifecycle'); END",
"trg_annotation_update": "BEFORE UPDATE ON submission_annotations WHEN NEW.submission_id IS NOT OLD.submission_id OR (NEW.source_annotation_id IS NOT OLD.source_annotation_id AND NOT (OLD.source_annotation_id IS NOT NULL AND NEW.source_annotation_id IS NULL)) OR NEW.category_id IS NOT OLD.category_id OR NEW.category_name IS NOT OLD.category_name OR NEW.start_time IS NOT OLD.start_time OR NEW.end_time IS NOT OLD.end_time OR NEW.start_frame IS NOT OLD.start_frame OR NEW.end_frame IS NOT OLD.end_frame OR NEW.confidence IS NOT OLD.confidence OR NEW.crop_region IS NOT OLD.crop_region OR NEW.mouse_ids IS NOT OLD.mouse_ids BEGIN SELECT RAISE(ABORT,'submission annotation immutable'); END",
"trg_annotation_delete": "BEFORE DELETE ON submission_annotations BEGIN SELECT RAISE(ABORT,'submission annotation immutable'); END",
"trg_raw_delete": "BEFORE DELETE ON raw_detections BEGIN SELECT RAISE(ABORT,'snapshot raw immutable') WHERE EXISTS(SELECT 1 FROM detection_snapshots WHERE detection_import_id=OLD.detection_import_id); END",
"trg_raw_update": "BEFORE UPDATE OF detection_import_id,frame_index,frame_detection_index,raw_track_id,box,keypoints,detection_confidence,class_id ON raw_detections BEGIN SELECT RAISE(ABORT,'snapshot raw immutable') WHERE EXISTS(SELECT 1 FROM detection_snapshots WHERE detection_import_id=OLD.detection_import_id) OR EXISTS(SELECT 1 FROM detection_snapshots WHERE detection_import_id=NEW.detection_import_id); END",
"trg_raw_insert": "BEFORE INSERT ON raw_detections BEGIN SELECT RAISE(ABORT,'snapshot raw immutable') WHERE EXISTS(SELECT 1 FROM detection_snapshots WHERE detection_import_id=NEW.detection_import_id); END",
}
def install_sqlite_authority_triggers(connection):
    for name, body in TRIGGERS.items(): connection.exec_driver_sql(f"CREATE TRIGGER IF NOT EXISTS {name} {body}")
def drop_sqlite_authority_triggers(connection):
    for name in TRIGGERS: connection.exec_driver_sql(f"DROP TRIGGER IF EXISTS {name}")
